name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker images
      - name: Build Backend Image
        run: |
          docker build -t salvini007/django_app_backend:latest ./backend
      - name: Build Frontend Image
        run: |
          docker build -t salvini007/react_app_frontend:latest ./frontend

      # Step 4: Push Docker images
      - name: Push Backend Image
        run: docker push salvini007/django_app_backend:latest
      - name: Push Frontend Image
        run: docker push salvini007/react_app_fronend:latest


